### PR TITLE
Alan's line that makes it great! Fixes big bugs

### PR DESCRIPTION
**Pull request by alanseiden**
Exercise for Sunshine PHP

### CODE REVIEW

**Comment by lornajane** [comment]
Thanks for this :)  As a general tip: make sure you branch for each thing you work on - usually I would reject a PR from someone's master branch because it means that you no longer have a clean master to branch from.  But really a minor detail, it was good to have your quick pull request to merge - thanks!

**Comment by alanseiden** [comment]
Thanks for the comment. I had thought it was correct to merge my feature branches into my master branch before pushing up to origin. Would it be better to push to a dev branch in my origin/remote repository, then submit a PR from that remote dev branch?

**Comment by lornajane** [comment]
Yes exactly!  So if I don't accept the pull request (or while I am working
on evaluating it), your master branch still matches the main project
master.  This means that you can branch your next feature off the master
branch without including any changes from any of your branches that haven't
been merged yet.  Hopefully that makes sense?

Lorna

On 5 February 2015 at 19:42, Alan Seiden notifications@github.com wrote:

> Thanks for the comment. I had thought it was correct to merge my feature
> branches into my master branch before pushing up to origin. Would it be
> better to push to a dev branch in my origin/remote repository, then submit
> a PR from that remote dev branch?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/lornajane/sunshinephp/pull/10#issuecomment-73112316.

## 

Lorna Mitchell
http://lornajane.net

**Comment by alanseiden** [comment]
Absolutely. Thank you for setting me straight on this, Lorna.

Alan

**Pull request merged**
